language: python
python:
  - "3.6"
  - "3.7"
env:
  - NUMPY_VERSION=1.15
  - NUMPY_VERSION=1.16
  - NUMPY_VERSION=1.19
install:
  - pip install numpy==$NUMPY_VERSION scipy matplotlib>=3 cython>=0.28
  - dev/build.sh
# command to run tests
script: dev/test.sh
